name: occupancy_net
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.1
  - pip=22.0.4
  - pyembree=0.1.6
  - python=3.8
  - pytorch=1.9.0
  - torchvision=0.10.0
  - pip:
    - Cython==0.29.28
    - h5py==3.6.0
    - imageio==2.16.2
    - matplotlib==3.5.1
    - numpy==1.22.3
    - pandas==1.4.2
    - Pillow==9.1.0
    - plyfile==0.7.4
    - pytest==7.1.1
    - PyYAML==6.0
    - scikit-image==0.19.2
    - scipy==1.8.0
    - setuptools==59.5.0
    - tensorboard==2.8.0
    - tqdm==4.64.0
    - trimesh==3.10.8
